services:
  my-db:
    container_name: my-db
    build: ./requirements/mariadb
    image: my-db
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
  
  my-wordpress:
    container_name: my-wordpress
    build: ./requirements/wordpress
    image: my-wordpress
    ports:
      - 9000:9000
    restart: always
    volumes:
      - vol:/var/www/html
    networks:
      - inception
    depends_on:
      - my-db

  my-nginx:
    container_name: my-nginx
    build: ./requirements/nginx
    image: my-nginx
    ports:
      - 443:443
    networks:
      - inception
    restart: always
    volumes:
      - vol:/var/www/html
    depends_on:
      - my-wordpress

networks:
    inception:

volumes:
  vol:
    driver: local
    driver_opts:
      type: none
      device: /home/drtaili/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/drtaili/data/database
      o: bind